vim.keymap.set("n", "-", "<cmd>Oil<CR>")
vim.keymap.set("n", "<leader>f", require("telescope.builtin").find_files, { noremap = true, silent = true })
vim.keymap.set("n", "<leader>g", require("telescope.builtin").live_grep, { noremap = true, silent = true })
vim.keymap.set("n", "<leader>*", require("telescope.builtin").grep_string, { noremap = true, silent = true })
vim.keymap.set("n", "<leader>h", require("telescope.builtin").highlights, { noremap = true, silent = true })
vim.keymap.set("n", "<leader>i", "<cmd>Inspect<CR>")
vim.keymap.set("n", "gt", "<cmd>BufferLinePick<CR>")
vim.keymap.set("n", "<leader>x", "<cmd>bd<CR>")
vim.keymap.set("n", "<leader>c", '"+y')
vim.keymap.set("v", "<leader>c", '"+y')
vim.keymap.set("n", "<leader>v", '"+p')
vim.keymap.set("v", "<leader>v", '"+p')
vim.keymap.set("n", "<leader>w", "gqq")
vim.keymap.set("n", "<leader>u", "vipJ")
