format = """
[░▒▓](white)\
[  ](bg:white fg:black)\
[](bg:bright-black fg:white)\
$directory\
[](fg:bright-black bg:black)\
$git_branch\
$git_status\
[](fg:black bg:black)\
$golang\
$lua\
$nodejs\
$ruby\
[](fg:black bg:black)\
$time\
[ ](fg:black)\
\n$character"""

[directory]
style = "fg:bright-white bg:bright-black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Code" = ""
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:black"
format = '[[ $symbol $branch ](fg:green bg:black)]($style)'

[git_status]
style = "bg:black"
format = '[[($all_status$ahead_behind )](fg:green bg:black)]($style)'

[golang]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:cyan bg:black)]($style)'

[lua]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:cyan bg:black)]($style)'

[nodejs]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:cyan bg:black)]($style)'

[ruby]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:cyan bg:black)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:bright-black"
format = '[[  $time ](fg:purple bg:black)]($style)'
