format = """
[░▒▓](#d8dee9)\
[  ](bg:#d8dee9 fg:#2e3440)\
[](bg:#4c566a fg:#d8dee9)\
$directory\
[](fg:#4c566a bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#3b4252)\
$ruby\
$nodejs\
$zig\
$lua\
[](fg:#3b4252 bg:#2e3440)\
$time\
[ ](fg:#2e3440)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#4c566a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Code" = ""
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[[ $symbol $branch ](fg:#a3be8c bg:#434c5e)]($style)'

[git_status]
style = "bg:#434c5e"
format = '[[($all_status$ahead_behind )](fg:#a3be8c bg:#434c5e)]($style)'

[ruby]
symbol = ""
style = "bg:#3b4252"
format = '[[ $symbol ($version) ](fg:#88c0d0 bg:#3b4252)]($style)'

[nodejs]
symbol = ""
style = "bg:#3b4252"
format = '[[ $symbol ($version) ](fg:#88c0d0 bg:#3b4252)]($style)'

[zig]
symbol = ""
style = "bg:#3b4252"
format = '[[ $symbol ($version) ](fg:#88c0d0 bg:#3b4252)]($style)'

[lua]
symbol = ""
style = "bg:#3b4252"
format = '[[ $symbol ($version) ](fg:#4c566a bg:#3b4252)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2e3440"
format = '[[  $time ](fg:#b48ead bg:#2e3440)]($style)'
